# Generated by Django 4.1 on 2022-08-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del director', max_length=150)),
                ('day_of_birth', models.DateField(blank=True, null=True)),
                ('day_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.director'),
        ),
    ]
