# Generated by Django 4.1 on 2022-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_director_remove_film_author_delete_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
